version: '3.8'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    expose:
      - "29092"  #  broker kafka PLAINTEXT acessivel aos outros contentores docker      
    ports:       #  broker kafka PLAINTEXT_HOST acessivel no localhost
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_BYTES=104857600  # 100 MiB em bytes
    healthcheck:
      test: kafka-topics.sh --list -bootstrap-server localhost:9092 || exit -1
      start_period: 25s                     # durante 25s não conta o número de tentativas falhadas
      interval: 10s
      timeout: 5s
      retries: 3 # Número máximo de tentativas falhadas depois de 10s
    volumes:
      - kafka-data:/bitnami/kafka
volumes:
  minio-data:
   driver: local
  kafka-data:
   driver: local
  etcd-volume:
   driver: local